### ISSUE TITLE
No "empty observable" warning when using a single empty Observable prop

### ISSUE THREAD

**Issue by andrei-zhidkov** [grammarly/focal#25]
Currently, there is an inconsistency between the single vs. multiple Observable props warning policies.
Namely, Focal will warn about empty observable in props only when there's more than one observable passed. The example is available [here](https://codesandbox.io/s/qzojqp73zq) (thanks @oleksiilevzhynskyi).
It looks like it's because `RenderMany` class reports the warning [right after walking the observables](https://github.com/grammarly/focal/blob/master/src/react/react.ts#L457), while `RenderOne` will warn the user only [after Observable's completion](https://github.com/grammarly/focal/blob/master/src/react/react.ts#L394), which may not happen at all.

Is there any specific reason for waiting for the completion in case of a single prop? It feels a bit misleading that the same issue is treated differently.

**Comment by blacktaxi** [comment]
Thanks for reporting!

Looks like a bug/misfeature. Since `Subject` doesn't immediately complete, it is not strictly empty, but I think it's still a valid case where a warning should be issued. I'm working on a fix in #26, please check it out and let me know whether it helps.

**Comment by blacktaxi** [comment]
Tracking this in #26 now
