### ISSUE TITLE
Problem with .view and unsubscribe

### ISSUE THREAD

**Issue by goloveychuk** [grammarly/focal#29]
After unsubscribing from `ReadonlyAtom` (created by .view) it still calling function inside, fails and unsubscribing.

In other words - if we unsubscribe from ReadonlyAtom - it don't unsubscribe from inner subscription. 

```ts
const state = Atom.create([{ id: 1 }])

  const view = state.view(state => state[0].id) //if we replace view with map - it works

  const sub = view.subscribe(s => {
    console.log(s)
  })

  state.modify(s => {
    sub.unsubscribe()
    return []
  })
```
This causing a problem with `reactiveList`.
```ts
{reactiveList(
        state.map(s => s.map((_, ind) => ind)),
        ind => {
          return <El el={state.view(s => s[ind].id)} /> //view is already unsubscribed from this observable, but `.view` is still calling. 
        }
  )}
```

I guess problem is here https://github.com/grammarly/focal/blob/master/src/atom/base.ts#L378

**Comment by blacktaxi** [comment]
Hi, thanks for the bug report. I've added tests to repro in #30 and will track the issue there.
