### ISSUE TITLE
Typescript error with strictNullChecks

### ISSUE THREAD

**Issue by jaked** [grammarly/focal#43]
Trying to use `focal` with Typescript 3.4.3, I get
```
node_modules/@grammarly/focal/dist/src/react/react.d.ts:103:5 - error TS2411: Property 'mount' of type 'undefined' is not assignable to string index type '((e: SyntheticEvent<any, Event>) => void) | ((domElement: Element | null) => void)'.

103     mount?: undefined;
        ~~~~~
```
and a similar error for `ref`. I'm able to get rid of the error if I turn off `strictNullChecks` in my `tsconfig.json`, but I don't want to do that :(.

Also I'm confused because the `tsconfig.json`s for `focal` has `strictNullChecks` turned on; in fact, I get the same error when I try to build the examples following the instructions.

Another way I found to fix it (without turning off `strictNullChecks`) is to remove the `mount?: undefined` and `ref?: undefined` lines from the type of `bindElementProps` in `react.d.ts`. I don't understand where those lines come from, given the code of `bindElementProps`; seems like a possible Typescript bug?

**Comment by Wenqer** [comment]
@jaked Could you please provide more details about your setup? Which versions of @types/react,@types/react-dom do you use? Even better be if you could provide a minimal reproducible case on some code sandbox (like https://codesandbox.io/), or in GitHub repo.

**Comment by jaked** [comment]
hi, thanks. I wasn't able to trigger the issue in CodeSandbox for some reason but here's a Github repo that fails locally for me: https://github.com/jaked/focal-typescript-bug

**Comment by jaked** [comment]
thank you!
