### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by teevik** [grammarly/focal#44]
Would it make sense to have a react hook, for example `useAtom` that would subscribe to the atom, and return the latest value?

For example, you'd use it something like this:
```jsx
import * as React from 'react'
import { Atom } from '@grammarly/focal'

const store = {
  count: Atom.create(0)
}

const Counter = () => {
  const count = useAtom(store.count)

  return (
    <div>Count: {count}</div>
  )
}
```

**Comment by blacktaxi** [comment]
For this particular example, I think it would be better to just use an `F.div` like this:

```ts
import { F } from '@grammarly/focal'

// ...

const Counter = () => {
  const count = store.count

  return (
    <F.div>Count: {count}</F.div>
  )
}
```

I would appreciate if you could provide some other examples so I could get a sense of what kind of problem you are having.

**Comment by teevik** [comment]
I guess I'm not really having any problems, just like the way hooks look 😅

But one use case could be using the result from useAtom in another hook, for example for updating the page title like they do at https://reactjs.org/docs/hooks-effect.html
```jsx
import React from "react"
import { Atom, useAtom } from "@grammarly/focal"

// ...

const Counter = () => {
  const count = useAtom(count)
  
  useEffect(() => {
    document.title = `You clicked ${count} times`
  }, [count])

  return <p>You clicked {count} times</p>
}
```

(although that's probably a terrible use case)

**Comment by blacktaxi** [comment]
That's actually a pretty good use case, although not very common. There is an easy way to do this kind of thing just by subscribing to the atom observable:

```ts
count.subscribe(x => {
  document.title = `You clicked ${x} times`
})
```

The problem with this is that there's no clean up – we never unsubscribe from the observable. You can deal with this type by having a special component that will manage the lifecycle of the side effect subscription. It's quite simple and could look like this:

```ts
class WithEffect extends React.Component<{ effect: () => Subscription }> {
  private _sub: Subscription | null = null

  private _unsubscribe() {
    if (this._sub) {
      this._sub.unsubscribe()
      this._sub = null
    }
  }

  componentDidMount() {
    if (this.props.effect) {
      this._sub = this.props.effect()
    }
  }

  componentDidUpdate() {
    if (this.props.effect) {
      this._unsubscribe()
      this._sub = this.props.effect()
    }
  }

  componentWillUnmount() {
    this._unsubscribe()
  }

  render() {
    return React.Children.only(this.props.children)
  }
}

// ...

const Counter = () =>
  <WithEffect effect={() => count.subscribe(x => `You clicked ${x} times`)}>
    <F.p>You clicked {count} times</F.p>
  </WithEffect>
```

Unfortunately this kind of utility component is not currently included in Focal.

**Comment by rileyatodd** [comment]
I think you could avoid managing the subscription yourself by leveraging the `tap` operator for the side effect.

```jsx
const setTitle = count => document.title = `You clicked ${count} times`

const Counter = () =>
  <F.p>You clicked {count.pipe(tap(setTitle))} times</F.p>
```

**Comment by Wenqer** [comment]
@rileyatodd that solution will work, but you will have problems when you decide to stop render {count} value into DOM and still updates it in the document.title.

@blacktaxi react hooks allow us to use a simpler solution then HOC:
```
function useSubscriptionTo(obs: Observable<unknown>) {
  React.useEffect(
    () => {
      const subs = obs.subscribe()
      return () => subs.unsubscribe()
    },
    [obs]
  )
}

...

const setTitle = count => document.title = `You clicked ${count} times`

const Counter = () => {
  useSubscriptionTo(count.pipe(tap(setTitle)))

  return <F.p>You clicked {count} times</F.p>
}
```
