### ISSUE TITLE
Uncaught TypeError: f.a.key is not a function

### ISSUE THREAD

**Issue by sukazavr** [grammarly/focal#66]
Hello!

I use Create React App. On dev environment everything goes well, but the production build goes broken.

```
base.ts:292 Uncaught TypeError: f.a.key is not a function
    at t.lens (base.ts:292)
    at Module.71 (state-app.ts:26)
    at l ((index):2)
    at Object.66 (main.c2bc3c36.chunk.js:1)
    at l ((index):2)
    at a ((index):2)
    at Array.e [as push] ((index):2)
    at main.c2bc3c36.chunk.js:1
```

Here is `base.ts` source map:
```
    AbstractAtom.prototype.lens = function (arg1) {
        // tslint:disable no-use-before-declare
        var args = [];
        for (var _i = 1; _i < arguments.length; _i++) {
            args[_i - 1] = arguments[_i];
        }
        // lens(prop expr) case
        return typeof arg1 === 'function'
            ? new LensedAtom(this, Lens.prop(arg1), structEq)
            // lens('key') case
            : typeof arg1 === 'string'
                ? new LensedAtom(this, Lens.compose.apply(Lens, [Lens.key(arg1)].concat(args.map(function (k) { return Lens.key(k); }))), structEq)
                // lens(lens) case
                : new LensedAtom(this, arg1, structEq);
        // tslint:enable no-use-before-declare
    };
    return AbstractAtom;
}(AbstractReadOnlyAtom));
```

Problem happens in this string:
`? new LensedAtom(this, Lens.compose.apply(Lens, [Lens.key(arg1)].concat(args.map(function (k) { return Lens.key(k); }))), structEq)
`

More precisely this sub-string: `Lens.compose.apply(Lens, [Lens.key(arg1)]`

Where is Lens.key is not a function.

I've tried to turn off mangle in TerserPlugin which minify the code and it had no results.

Now I'm thinking about the sequence of function calls, mb it works differently in dev and prod env.

I hope you have some ideas what should I try next to make it works.
You can explore the source-code here: https://github.com/sukazavr/dego.app
And of course you can build it on your local machine and test it out by yourself.
Thank you!

**Comment by sukazavr** [comment]
Also you can run this broken build here: https://dego.app/ (it has source-maps)

**Comment by sukazavr** [comment]
Experimentally, I found out that you have a broken esm5 build
If I remove `"module": "dist/_esm5/src/index.js",` line from `node_modules\@grammarly\focal\package.json` everything works well

**Comment by blacktaxi** [comment]
Hi, thanks for reporting and sorry this happened! Maybe @A-gambit can give more ideas about a proper fix?

**Comment by YanivSilberman** [comment]
Has anyone figured this out?
