### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by ituaijagbone** [grammarly/focal#83]
Is there going to be any support for React 17?

**Comment by oleksiilevzhynskyi** [comment]
Hey. Thanks for your interest in Focal.

@grammarly/focal should be complatible with [React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html). I will double-check this next week and allow React 17 in "peerDependencies".

Other than that, we're working toward support React beyond version 17. Here is MR that rewrites deprecated lifecycle to hooks - https://github.com/grammarly/focal/pull/82/files

**Comment by ituaijagbone** [comment]
Awesome. Thank you!
